import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Card } from 'src/components';
import { IAllCarsResponse } from 'src/shared/interfaces';
import { getAllCars } from 'src/shared/services';
import { BackgroundMain, Content } from 'src/shared/styles/main-page';

interface HomeProps {
	cars: IAllCarsResponse[];
}

export default function Home({ cars }: HomeProps) {
	// console.log(cars);

	return (
		<BackgroundMain>
			<Head>
				<title>Exotic Cars - Main</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Content>
				{cars.map((car) => (
					<Link href="/" key={car.id}>
						<a>
							<Card car={car} />
						</a>
					</Link>
				))}
			</Content>
		</BackgroundMain>
	);
}

export const getStaticProps: GetStaticProps = async () => {
	const cars = await getAllCars();
	return {
		props: {
			cars,
		},
		revalidate: 60 * 60 * 24, //24h
	};
};
